#:kivy 2.1.0
BoxLayout:
    orientation:"vertical"
    MDBottomNavigation:
        # Color stuff
        MDBottomNavigationItem:
            name:"screen 1"
            text:"Gérer les listes"
            icon:""
            MDLabel:
                text:"Python"
                halign:"center"
        MDBottomNavigationItem:
            name:"screen 2"
            text:"Imprimer des fiches"
            icon:""
            MDLabel:
                text:"Python"
                halign:"center"